version: '3.8'

services:
  catalog:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    networks:
      - emporium-network

networks:
  emporium-network:
    driver: bridge
