services:
  catalog-primary:
    build: .
    ports:
      - "5001:5000"
    environment:
      - ROLE=primary
      - PEER_URL=http://catalog-backup:5000
      - CACHE_INVALIDATE_URL=http://localhost:3000/cache/invalidate  # Will be updated when gateway is ready
    networks:
      - bazar-network

  catalog-backup:
    build: .
    ports:
      - "5002:5000"
    environment:
      - ROLE=backup
      - PEER_URL=http://catalog-primary:5000
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge
